//
// DO NOT EDIT THIS FILE, IT HAS BEEN GENERATED USING AndroidAnnotations 3.0.1.
//


package me.risky.jingdong.adapter;

import android.content.Context;

public final class ListItemAdapter_
    extends ListItemAdapter
{

    private Context context_;

    private ListItemAdapter_(Context context) {
        super(context);
        context_ = context;
        init_();
    }

    public static ListItemAdapter_ getInstance_(Context context) {
        return new ListItemAdapter_(context);
    }

    private void init_() {
    }

    public void rebind(Context context) {
        context_ = context;
        init_();
    }

}
